name: ironly
description: A new dynamic laundry app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Updated for latest Flutter/Dart

dependencies:
  flutter:
    sdk: flutter

  # ✅ Location packages (already included)
  google_maps_flutter: ^2.6.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  google_sign_in: ^6.0.0
  app_links: ^6.1.4

  # ✅ Core dependencies (already included)
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.3.1
  material_design_icons_flutter: ^7.0.7296
  flutter_slidable: ^4.0.0
  animated_background: ^2.0.0
  url_launcher: ^6.1.14
  lucide_icons: ^0.257.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.7.0
  razorpay_flutter: ^1.3.5
  flutter_speed_dial: ^7.0.0
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  pdf: ^3.10.4
  path_provider: ^2.1.1
  share_plus: ^11.0.0

  # ✅ UPDATED: Firebase & Notifications - Latest versions
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.1.0  # ✅ LATEST VERSION
  timezone: ^0.10.1  # ✅ Updated for latest compatibility
  permission_handler: ^12.0.1  # ✅ Latest version

  # ✅ Supabase packages (already included)
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1

  # ✅ Image & file support (already included)
  image_picker: ^1.0.4
  path: ^1.9.0

  # ✅ State management (already included)
  provider: ^6.1.2

  # ✅ Localization support (already included)
  easy_localization: ^3.0.3
  flutter_localizations:
    sdk: flutter

  # ✅ Internationalization (already included)
  intl: ^0.20.2

  # ✅ Animation support (already included)
  lottie: ^3.1.0

  # ✅ Enhanced packages for slot selection system
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.4
  flutter_typeahead: ^5.2.0
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/speed_iron_logo.png
    - assets/images/app_logo.png
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/banner3.png
    - assets/images/banner4.png
    - assets/images/banner5.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/boys.png
    - assets/images/girls.png
    - assets/images/essential.png
    - assets/images/google_logo.png  # ✅ ADDED YOUR GOOGLE LOGO

    # ✅ Product icons used in orders screen
    - assets/images/shirt.png
    - assets/images/pants.png
    - assets/images/kurti.png
    - assets/images/saree.png
    - assets/images/tshirt.png
    - assets/images/frock.png
    - assets/images/bedsheet.png
    - assets/images/towel.png
    - assets/images/iron_icon.png

    # ✅ Config file
    - .env

    # ✅ Language files
    - assets/lang/
    - assets/translations/

    # ✅ Animations
    - assets/animations/empty_cart.json
